# Generated by Django 5.2.5 on 2025-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('salt', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=64)),
                ('role', models.CharField(default='Citizen', max_length=20)),
            ],
        ),
    ]
